

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Services to be used by Microservices.
  config.vm.define "services" do |server| 

    server.vm.box = "williamyeh/ubuntu-trusty64-docker"

    server.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end  
    
    server.vm.network "private_network", ip: "192.168.33.10"

    server.vm.provision "file", source: "./prometheus.yml", destination: "/home/vagrant/prometheus.yml"

    # Hack - Docker provisioner didn't seem to want to run this in Serial.
    server.vm.provision "shell", 
      inline: "docker run -v /tmp/prom:/tmp/prom -e DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3 prom/promdash ./bin/rake db:migrate"

    server.vm.provision "docker" do |d|
      d.run "progrium/consul",
        args: "-p 8300:8300 -p 8301:8301 -p 8301:8301/udp -p 8302:8302 -p 8302:8302/udp -p 8400:8400 -p 8500:8500 --name consul1",
        cmd: "-server -bootstrap -ui-dir /ui -advertise 192.168.33.10"
      d.run "elasticsearch:1.7.3",
        args: "-p 9200:9200 -p 9300:9300 --name elasticsearch1"
      d.run "prom/promdash",
        args: "-p 3000:3000 -v /tmp/prom:/tmp/prom -e DATABASE_URL=sqlite3:/tmp/prom/file.sqlite3"
    end

    # Hack - this command fails with Docker provisioner
    server.vm.provision "shell",
      inline: "docker run -d -p 9090:9090 -v /home/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus:0.16.0rc1"

    server.vm.provision "shell",
      inline: "docker run -d --link elasticsearch1:elasticsearch -p 5601:5601 kibana:4.1.2"

  end  
  
  # Mesos Cluster
  config.vm.define "mesos" do |mesos|

    mesos.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    mesos.vm.network "private_network", ip: "10.141.141.10"

    # playa-mesos has an old version of docker that is not compatible w/ the docker provisioner
    mesos.vm.provision "shell",
      inline: "sudo docker run -d -p 8300:8300 -p 8301:8301 -p 8301:8301/udp -p 8302:8302 -p 8302:8302/udp -p 8400:8400 -p 8500:8500 progrium/consul -advertise 10.141.141.10 -join 192.168.33.10"
    
    mesos.vm.provision "shell",
      inline: "sudo docker run -d -p 51515:51515 logstash:1.5 -e 'input { tcp { port => 51515 codec => json_lines } } output { elasticsearch { host => \"192.168.33.10:9200\" protocol => \"http\" } }'"
    
    mesos.vm.box = "rickfast/mesos-marathon-docker"
  end

end
